### ISSUE TITLE
Search in layer that has been filtered gives error message

### ISSUE THREAD

**Issue by Dalneberg** [Eskilstuna-kommun/ek-search-plugin#5]
**Is your feature request related to a problem? Please describe.**
When a filter has been made and when a search on that filtered layer is done it gives an errormessage. For example:
GetMap KVP request contained conflicting filters. Filter: [[ sokid = 210 ]], fid: [], cql: [[title = Stenmansgatan ]]

**Describe the solution you'd like**
By make a change in eksearch.js for ek_search_plugin such that it filters with cql_filter in ECQL instead of filter in OGC XML.

From this:
```js
const QueryString = encodeURI(['service=WFS',
      '&version=1.1.0',
      `&request=GetFeature&typeNames=${searchHitLayerName}`,
      '&outputFormat=json',
      `&filter=<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc"><ogc:PropertyIsEqualTo><ogc:PropertyName>${queryAttribute}</ogc:PropertyName><ogc:Literal>${id}</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>`
    ].join(''));
```

and:
```js
if (targetInfoLayer === layer) { // The normal case. If not then there will be no id for the estateLayerName
        featureInfoUrlTextHtml += encodeURI(`&filter=<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc"><ogc:PropertyIsEqualTo><ogc:PropertyName>${queryAttribute}</ogc:PropertyName><ogc:Literal>${id}</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>`);
      }
```

To this:
```js
const cqlFilter = encodeURIComponent(`${queryAttribute} = '${id}'`);

    const QueryString = (['service=WFS',
      '&version=1.1.0',
      `&request=GetFeature&typeNames=${searchHitLayerName}`,
      '&outputFormat=json',
      `&cql_filter=${cqlFilter}`
    ].join(''));
```

and:
```js
if (targetInfoLayer === layer) { // The normal case. If not then there will be no id for the estateLayerName
        featureInfoUrlTextHtml += `&cql_filter=${cqlFilter}`;
      }
```

**Comment by Grammostola** [comment]
I revise my previous statements on the matter: this is about WFS and getFeature and both QGIS server https://docs.qgis.org/3.34/en/docs/server_manual/services/wfs.html#wfs-getfeature-filter and ESRI WFS services https://enterprise.arcgis.com/en/server/latest/publish-services/linux/communicating-with-a-wfs-service-in-a-web-browser.htm appear to support this part of the OGC standard. 

Therefore the better target, in my opinion, is https://github.com/Eskilstuna-kommun/ek-filter-plugin/tree/master (change from cql filter -> filter there)
